server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create


#spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3306/tutorial
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password: 1234
#  jpa:
#    open-in-view: false
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update