server:
  port: 9090

spring:
  datasource:
    url: jdbc:mariadb://gymbuddy.cafe24.com:3306/gymbuddy
    driver-class-name: org.mariadb.jdbc.Driver
    username: gymbuddy
    password: myang2526!
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update